name: Executing Scripts Workflow
run-name: Executing Scripts Workflow
on: push
jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List and Read File
        run: |
          chmod +x ascii-script.sh
          ./ascii-script.sh
